package mysql

// https://dev.mysql.com/doc/internals/en/command-phase.html
const (
	COM_SLEEP byte = iota
	COM_QUIT
	COM_INIT_DB
	COM_QUERY
	COM_FIELD_LIST
	COM_CREATE_DB
	COM_DROP_DB
	COM_REFRESH
	COM_SHUTDOWN
	COM_STATISTICS
	COM_PROCESS_INFO
	COM_CONNECT
	COM_PROCESS_KILL
	COM_DEBUG
	COM_PING
	COM_TIME
	COM_DELAYED_INSERT
	COM_CHANGE_USER
	COM_BINLOG_DUMP
	COM_TABLE_DUMP
	COM_CONNECT_OUT
	COM_REGISTER_SLAVE
	COM_STMT_PREPARE
	COM_STMT_EXECUTE
	COM_STMT_SEND_LONG_DATA
	COM_STMT_CLOSE
	COM_STMT_RESET
	COM_SET_OPTION
	COM_STMT_FETCH
	COM_DAEMON
	COM_BINLOG_DUMP_GTID
	COM_RESET_CONNECTION
)

// Shutdown subcommand
const (
	SHUTDOWN_DEFAULT byte = iota
	SHUTDOWN_WAIT_CONNECTIONS
	SHUTDOWN_WAIT_TRANSACTIONS
	SHUTDOWN_WAIT_UPDATES          byte = 0x08
	SHUTDOWN_WAIT_ALL_BUFFERS      byte = 0x10
	SHUTDOWN_WAIT_CRITICAL_BUFFERS byte = 0x11
	KILL_QUERY                     byte = 0xfe
	KILL_CONNECTION                byte = 0xff
)
